# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UTD', '0003_auto_20160407_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.TextField()),
                ('link', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTD.Album')),
            ],
        ),
        migrations.CreateModel(
            name='UserArtistsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='related',
            field=models.ManyToManyField(related_name='_artist_related_+', to='UTD.Artist'),
        ),
        migrations.AddField(
            model_name='userartistslist',
            name='followed_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTD.Artist'),
        ),
        migrations.AddField(
            model_name='userartistslist',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
