# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTD', '0004_auto_20160414_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userartistslist',
            old_name='user_name',
            new_name='user',
        ),
    ]
